// Example arrays
const array1 = ["Ahhh", "Antidote"
,"Bang"
,"Barrier"
,"BazooCall"
,"BeastCut"
,"Beat"
,"BeDragon"
,"Beserker"
,"BiAttack"
,"BigBang"
,"BigTrip"
,"BirdBlow"
,"BladeD"
,"Blaze"
,"BlazeAir"
,"Blazemore"
,"Blazemost"
,"Blizzard"
,"Bolt"
,"BoltSlash"
,"Boom"
,"Bounce"
,"Branching"
,"CallHelp"
,"Chance"
,"ChargeUP"
,"CleanCut"
,"Cover"
,"Curse"
,"CurseOff"
,"DanceShut"
,"DeChaos"
,"Defeat"
,"Defence"
,"DeMagic"
,"DevilCut"
,"DiagoCall"
,"Dodge"
,"DrakSlash"
,"EerieLite"
,"EvilSlash"
,"Explodet"
,"Farewell"
,"FireAir"
,"Firebal"
,"Firebane"
,"Firebolt"
,"FireSlash"
,"Focus"
,"FrigidAir"
,"GigaSlash"
,"Guardian"
,"Heal"
,"HealAll"
,"HealMore"
,"HealUs"
,"HealUsAll"
,"HellBlast"
,"HighJump"
,"Hustle"
,"IceAir"
,"IceBolt"
,"IceSlash"
,"IceStorm"
,"Imitate"
,"Increase"
,"Infermore"
,"Infermost"
,"Infernos"
,"Ironize"
,"K.O.Dance"
,"Kamikaze"
,"LegSweep"
,"LifeDance"
,"LifeSong"
,"Lightning"
,"LureDance"
,"LushLicks"
,"MagicBack"
,"MagicWall"
,"MapMagic"
,"Massacre"
,"Meditate"
,"MegaMagic"
,"MetalCut"
,"MouthShut"
,"MultiCut"
,"NapAttack"
,"NumbOff"
,"OddDance"
,"PalsyAir"
,"PanicAll"
,"PaniDance"
,"Paralyze"
,"PoisonAir"
,"PoisonGas"
,"PoisonHit"
,"PsycheUp"
,"QuadHits"
,"Radiant"
,"RainSlash"
,"Ramming"
,"Revive"
,"RobMagic"
,"RockThrow"
,"Sacrifice"
,"SamsiCall"
,"SandStorm"
,"Sap"
,"Scorching"
,"Sheldodge"
,"SickLick"
,"SideStep"
,"Sleep"
,"SleepAir"
,"SleepAll"
,"Slow"
,"SlowAll"
,"Smashlime"
,"SnowStorm"
,"Speed"
,"SpeedUp"
,"SquallHit"
,"StepGuard"
,"StopSpell"
,"StormWind"
,"StrongD"
,"SuckAir"
,"SuckAll"
,"Surge"
,"Surround"
,"TailWind"
,"TakeMagic"
,"TatsuCall"
,"ThickFog"
,"Thordain"
,"Transform"
,"TwinHits"
,"TwinSlash"
,"UltraDown"
,"Upper"
,"VacuSlash"
,"Vacuum"
,"Vivify"
,"WarCry"
,"Whistle"
,"WhiteAir"
,"WhiteFire"
,"WindBeast"
,"YellHelp"
,"Zap"
, "ZombieCut"];

const array2 = ["    Female foe: Stops action for 1 turn Male foe: Damage to one foe", "Cures poison to one ally", "    20-30 Explosion Damage to all foes", " Reduces Fire and Ice breath damage by 50% for the rest of the fight", "Summons a Bazoo that uses IceStorm,Hellblast,DeMagic to fight with", "50% more Damage to beasts Normal against other foes", "    Instant death to one foe", "Transforms you into a dragon for the rest of the fight with skills: SnowStorm,Scorching,DeMagic", "Normal attack with increased Damage and defence at 0", "Attacks twice one turn with 75% strength", " 300-400 Explosion Damage to all foes", " Trips all foes and stops their actions for 1 turn", "50% more Damage to birds Normal against other foes", "  Halves the Damage inflicted by the foe from physical attacks and reflects the Damage taken 50% of the time", "   12-15 Fire Damage to one foe", "32-48 Fire Damage to all foes", "70-90 Fire Damage to one foe", "180-200 Fire Damage to one foe", "80-104 Ice Damage to all foes", "    35-50 Lightning Damage to all foes", "Normal attack based on Lightning resistance of the foe", "    52-68 Explosion Damage to all foes", "  Reflects spells back at opponents", "50% more damage to plants Normal against other foes", "Calls randomly allies to help,level based Damage", "  Casts a random effect - Can be good or bad", "Additional Damage next turn.", "50% more damage to Materials Normal against other foes", "   Takes the attack against one ally", "   Curses all foes,random effects", "Remove the curse from one ally", "Suspends all foes Dance attacks", " Cures confusion", "  Instant death to all foes", " Decreases defense of all foes by 50%", " Dispels magic effects on all foes (Upper,Speed,Barrier,MagicWall)", "50% more Damage to Devils Normal against other foes", "Summons a Diago that uses TwinHits,SickLick,Scorching to fight with", "   Changes the target of a physical attack against the caster 20% Chance target is an ally, 80% Chance target is an enemy", "50% more damage against Dragons Normal against other foes", "Lowers magic resistance for all foes", "Physical Damage based on the attack of user", "130-140 Explosion Damage to all foes", "Revives all allies and causes instant death to the caster", " 14-22 Fire Damage to all foes", " 16-24 Fire Damage to all foes", "30-42 Fire Damage to all foes", "88-112 Fire Damage to all foes", "Normal attack based on Fire resistance of the foe", "   Two attacks next turn", "16-24 Ice Damage to all foes ", "350-410 Damage to one foe", "Takes all attacks for one turn", "    Heals 30-40 Hp for one ally", " Heals all Hp for one ally", "Heals 75-90 Hp for one ally", "  Heals 90-120 Hp for all allies", "Heals all Hp for all allies", "210-290 Lightning Damage to all foes", "Jump into the Air and attack next turn with increased attack", "  Heals 70-80 Hp for all allies", "  42-54 Ice Damage to all foes", " 25-35 Ice Damage to all foes", "Normal attack based on Ice resistance of the foe", "82-112 Ice Damage to all foes", " Copy and return every skill cast on Caster for 1 turn", "Increases defence for all allies by 50%", "25-55 Air Damage to all foes", "80-180 Air Damage to all foes", "8-24 Air Damage to all foes", " All allies become invulernable for 3 turns [but can't move]", "Instant death to all foes", "Reduces foe's Hp to 1 and attacker's Hp to 1 if successful", "Trips one foe and stops his action for 1 turn", "Revives all allies and causes instant death to the caster", "Revives all allies (requires 2 turns and can fail)", "40-60 Lightning Damage to all foes", "Stops actions of all foes for one turn by inviting them to dance", "Stops the action of one foe for one turn", "Reflects back a skill once to the foes", "Increases resistance against foes' skills", "Reveals whole map of current level inside a gate", "Inflicts 95-105% of the caster's attack against one random monster", "Heals 500 Hp to the caster in combat only", "Highest Damage spell to all foes", "50% more Damage against Metal monsters, Normal against other foes", "Suspends one foe's breath attack", "180-210 Cut Damage to all foes", "Normal attack and tries to sleep the foe", " Cures paralysis or wakes an ally", "Lowers one foe's Mp depending on the caster's level", "Breathes Air to paralyze all foes", "Confuses all foes", "Confuses or paralyzes all foes", "Normal attack and tries to paralyze the foe", "Breathes gas to poison all foes", "Breathes Air to poison all foes ", "Normal attack and tries to poison the foe", "Greater Damage with normal attack after end of this turn", "Attacks 4 times random foes", " Decreases physical hit chance of all foes", "Physical attack against all foes", " Reduces the foe's Hp by 50% and hurts the caster too", "  Restores life to one ally with full Hp", "Steals one foe's Mp", "75-100 Damage with rocks to all foes", "Causes instant death or close to it to all foes and caster", "Summons a Samsi to fight using EvilSlash,SquallHit,RainSlash", "Decreases hit chance of all foes", "     Decreases defense of one foe by 50%", "75-100 Fire Damage to all foes", "50% more damge against Bugs Normal against other foes", "Stops action of one foe and reduces his defense to 1 for one turn", "Increase chance to dodge foes' attacks", "   Puts one foe to sleep", "Puts all foes to sleep", "Puts all foes to sleep", "    Decreases agility of one foe by 50%", " Decreases agility of all foes by 50%", "50% more Damage against Slimes Normal against other foes", "42-58 Ice Damage to all foes", "   Increases agility of one foe by 50%", " Increases agility of all foes by 50%", "Physical Attack which lets you always attack first this turn", "Prevents Damage from lava, swamp, barrier for 1 level inside Gates", "Suspends all magical skills of all foes", "Reflects breath attacks to all foes ", " Reduces every Damage taken this turn by 90%", " More Damage next turn with breath skills", " Sucks in all attacks targeted at one ally for one turn", "   Cures any ailments for all allies", "Decreases hit chance of all foes", "Reflects breath attacks to one foe", "Absorbs Mp of one spell cast by foe", "Summons a Tatsu using HealMore,Lightning,Cover", "Suspends the skills of everyone for one round", "175-225 Lightning Damage to all foes", "Transforms a monsters skills and stats to those of the selected foe", "Increases the amount of Damage of the physical attacks", "Inflicts physical Damage against one foe and wounds yourself", "Casts Sap,Slow,Surround on one foe ", "   Increases defence for one ally by 50%", "Normal attack based on Air resistance of the foe", "  Air Damage to all foes,level based", "  Restores life to one ally with half his Hp (50% chance of sucess)", "  Freezes all foes with a loud roar to stop  their actions for 1 turn", " Summons monsters inside the gates to fight you", "160-180 Ice Damage to all foes", "150-170 Fire Damage to all foes", "Air Damage to one foe,level based", "Calls randomly allies to help,level based Damage", "     70-90 Lightning Damage to all foes", "50% more Damage against Zombies Normal against other foes",];

console.log(array1.length);
console.log(array2.length);
// Function to combine arrays into an object
function arraysToObject(names, descriptions) {
    if (names.length !== descriptions.length) {
        throw new Error("Both arrays must have the same length.");
    }

    const skills = names.map((name, index) => ({
        name: name,
        description: descriptions[index]
    }));

    return { skills };
}

const skillsObject = arraysToObject(array1, array2);

// Ensure you have this line to display output
console.log(JSON.stringify(skillsObject, null, 2));